/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flashcardshark.bean;

import flashcardshark.utils.DataAnalyzer;
import java.util.*;

/**
 *
 * @author maximilian.bisesi
 */
public class UserAccount {
    //userid is the same as the autogenerated id in the database...
    private String userName;
    private String password;
    private String firstname;
    private String lastname;
    private String email;
    private String userid;
    private String cardlistsize;
    private String rank;
    private Integer points;
    private String avatar;

    //hold the different lists of cards
    //all cards is slot 0
    //filtered cards is slot 1
    //use slot two for studied cards
    private ArrayList<ArrayList<Card>> cards = new ArrayList<>();
    private boolean useFilter = false;
    private boolean studying = false;
    
    public UserAccount(String uname,String pword, String fname, String lastname, String email,String rank, Integer points, String avatar) {
        this.userName = uname;
        this.password = pword;
        this.firstname = fname;
        this.lastname = lastname;
        this.email = email;
        this.points = points;
        this.rank = rank;
        //this.avatar = avatar;
        //populate the cards list with values to fill
        cards.add(new ArrayList<>());
        cards.add(new ArrayList<>());
        cards.add(new ArrayList<>());
    }
    
    public UserAccount(String uname,String pword, String fname, String lastname, String email, String userid,Integer points) {
        this.userName = uname;
        this.password = pword;
        this.firstname = fname;
        this.lastname = lastname;
        this.email = email;
        this.userid = userid;
        this.points = points;
        this.rank = DataAnalyzer.determineRank(points);
        cards.add(new ArrayList<>());
        cards.add(new ArrayList<>());
        cards.add(new ArrayList<>());
    }
    
    public UserAccount(String uname,String pword, String fname, String lname, String email){
        this.userName = uname;
        this.password = pword;
        this.firstname = fname;
        this.lastname = lname;
        this.email = email;
        cards.add(new ArrayList<>());
        cards.add(new ArrayList<>());
        cards.add(new ArrayList<>());
    }
    
    public void filterCards(String[] cats) {
        ArrayList<Card> filteredCards = new ArrayList<>();
        for(Card c : cards.get(0)) {
            
            for(String selectedCategory : cats) {
                
                if(c.getCategory().equals(selectedCategory)){
                    filteredCards.add(c);
                }
                
            }
        }
        System.out.println("filtered cards size: "+filteredCards);
        cards.set(1, filteredCards);
    }
    
    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    
    
    public ArrayList<Card> getCards(){
        if(useFilter) {
            return cards.get(1);
        }else if(studying) { 
            return cards.get(2);
        } else 
            return cards.get(0);
    }    

    public ArrayList<Card> getAllCards(){
        return cards.get(0);
    }
    
    public void filter() {
        useFilter = true;
        studying = false;
    }
    
    public void dontFilter() {
        useFilter = false;
    }
    
    public String getUserName() {
        return userName;
    }
 
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    
    public String getUserID(){
        return userid;
    }
    
    public void setUserID(String id) {
        userid = id;
    }
    
    public void addCards(ArrayList<Card> cards){
        //assign list of cards to users, this could only get tricky if a user logs in then logs out then logs back in...
        this.cards.set(0, cards);
        this.cardlistsize = Integer.toString(cards.size());
    }
    
    public String getCardListSize() {
        return cardlistsize;
    }
    
    public String getRank(){
        return rank;
    }
    
    public Integer getPoints(){
        return points;
    }
    
    @Override
    public boolean equals(Object o){
        if(o instanceof UserAccount && ((UserAccount)o).getUserID().equals(this.userid)){
            return true;
        } 
        return false;
    }
    
    @Override
    public int hashCode(){
        return Objects.hash(userid);
    }
    
}